FROM airbyte/server:0.50.24

ENV AIRBYTE_VERSION=0.50.24
ENV PORT=8001
ENV DATABASE_USER=${POSTGRES_USER}
ENV DATABASE_PASSWORD=${POSTGRES_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}
ENV MICRONAUT_ENVIRONMENTS=control-plane
ENV DATABASE_PROPERTIES='{"ssl":true}'
ENV airbyte.workspace.root=/data
ENV CONFIG_ROOT=/config

EXPOSE 8001
