version: '3.7'
services:
  airbyte-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=airbyte
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILWAY_VOLUME_MOUNT=/data
    volumes:
      - /data:/var/lib/postgresql/data

  airbyte-scheduler:
    image: airbyte/scheduler:latest
    environment:
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
      - RAILWAY_VOLUME_MOUNT=/workspace
      - CONFIG_ROOT=/config
    volumes:
      - /workspace:/workspace
      - /config:/config
    depends_on:
      - airbyte-db

  airbyte-worker:
    image: airbyte/worker:latest
    environment:
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
      - RAILWAY_VOLUME_MOUNT=/workspace
      - CONFIG_ROOT=/config
    volumes:
      - /workspace:/workspace
      - /config:/config
    depends_on:
      - airbyte-db

  airbyte-server:
    image: airbyte/server:latest
    environment:
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
      - CONFIG_ROOT=/config
      - PORT=80
    volumes:
      - /config:/config
    depends_on:
      - airbyte-db

  airbyte-webapp:
    image: airbyte/webapp:latest
    environment:
      - AIRBYTE_API_SERVER_HOST=${RAILWAY_PUBLIC_DOMAIN}
      - AIRBYTE_API_SERVER_PORT=80
      - PORT=80
    depends_on:
      - airbyte-server
