FROM airbyte/server:0.50.24

ENV AIRBYTE_VERSION=0.50.24
ENV PORT=8001
ENV TRACKING_STRATEGY=logging
ENV WEBAPP_URL=${RAILWAY_PUBLIC_DOMAIN}
ENV DATABASE_USER=postgres
ENV DATABASE_PASSWORD=${POSTGRES_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}

EXPOSE 8001
